# Generated by Django 4.2.2 on 2023-07-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productsmodel_name_alter_productsmodel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='types',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'fourth')], default=1, max_length=4),
        ),
    ]
