# Generated by Django 4.2.2 on 2023-07-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productsmodel_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productsmodel',
            table='Products',
        ),
    ]
